### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by cerebrumbr** [magento/magento2-samples#26]
See images.

After run composer update

Return this messages ...

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/sample-bundle-all could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

![img01](https://cloud.githubusercontent.com/assets/2263217/6888373/98893a40-d651-11e4-9b6a-6df3a69f6abe.png)

![img02](https://cloud.githubusercontent.com/assets/2263217/6888375/9e9da268-d651-11e4-8d61-48e407f0a448.jpg)

**Comment by TexanHogman** [comment]
Yes you are correct we have not published the samples to packages.magento.com but this will be done very soon.  As you can see from the two currently available, they demonstrate very little functionality.  Under review right now are 7 additional samples that really will start to M2 technology and best practices.  Check back in a week and they should be merged to the public github repo as well as be published to packages.magento.com.

**Comment by TexanHogman** [comment]
now that the samples are updated, will you try again?

**Comment by sivajik34** [comment]
still issue there.

**Comment by otoolec** [comment]
Can you try adding the following to your root composer.json file? 

```json
    "repositories": [
        {
            "type": "composer",
            "url": "http://packages.magento.com/"
        }
    ]
```

**Comment by sivajik34** [comment]
now working fine

**Comment by AguNnamdi** [comment]
Save yourself from headache and run the following:

apt-get install apache2 php php-cli mysql-server php-mysql libapache2-mod-php php-mcrypt php-mbstring php-imap phpunit
