### ISSUE TITLE
Sample payment method does not show in checkout

### ISSUE THREAD

**Issue by rhoerr** [magento/magento2-samples#38]
The sample payment method does not display on frontend checkout. This is probably related to recent checkout changes, but I'm not sure. My best guess is it needs view files (layout XML/JS) to actually register it as an option, and there are none included.

**Comment by muasir** [comment]
There have been some rework in payment module, so we will be removing the payment-provider sample.

**Comment by dkvashninbay** [comment]
Hi!
Please use the new Payment Gateway integration sample https://github.com/magento/magento2-samples/tree/master/sample-module-payment-gateway

**Comment by OnTapKristjan** [comment]
@dkvashninbay can you clarify when Magento_Vault will be released? We're building a payment extension based on new gateway integration and we need to add tokenisation support, however Vault is currently not compatible with the recent released version, so for now I've taken the approach porting it back to release version just so we can use it. The payment extension shall be released before Imagine '16 so there is no way we can use the 'develop' version of Magento2.

**Comment by refaelgold** [comment]
try to activate the module from advanced/vadvanced at admin panel
