### ISSUE TITLE
Sample modules installable but still 404

### ISSUE THREAD

**Issue by Pinimichu** [magento/magento2-samples#47]
Hi all,
I have tried to install the following sample components on my local VM;
- sample-module-form-uicomponent
- sample-module-newpage
- sample-module-servicecontract-new
- sample-module-webflow

The installation with bin/magento setup:upgrade was successfully and the modules are avaialable in the admin panel. But if I try to open the example pages I still get "404 Not found".
I used the URL from the readmes e.g. <magento2-url>/webflow/firstpage
I have tried the latest version including registration.php. 

Issue or any other ideas?
Thanks.

Edit: Developer mode is enabled, too.

**Comment by xcomSteveJohnson** [comment]
Hi, I reproduced the 404. I think the README instructions should be modified; I'll enter a PR soon.

What I had done wrong is to name the directory `SampleWebflow` instead of `SampleWebFlow`. Check that;  compare your directory name against the component's `registration.php` (which shows the correct path).

**Comment by Pinimichu** [comment]
Okay, I think I found the issue. I did not know that I had to rename the "sample-module-..." directory to "SampleWebFlow" as defined inside registration.php. I am not familar with magento and did not recognize the relation... As far as I can see the renaming is not included in the readmes. I would suggest to add it for noobs like me.
Thanks for your help! Can be closed I guess.

**Comment by xcomSteveJohnson** [comment]
We're working on improving the instructions, thanks.
