### ISSUE TITLE
Error while installing using composer in magento 2.07

### ISSUE THREAD

**Issue by mnjenga** [magento/magento2-samples#65]
Kindly assist, I am getting below error when I attempt to install the sample

C:\Apache24\htdocs\abigail\vendor\magento\sample-module-payment-gateway>composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/module-sales could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package magento/module-checkout could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package magento/module-payment could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package magento/framework could not be found in any version, there may be a typo in the package name.
  Problem 5
    - The requested package magento/magento-composer-installer 100.0.* exists as magento/magento-composer-installer[0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, dev-master] but these are rejected by your constraint.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Kindly advice where I could be going wrong.

**Comment by frostshoxx** [comment]
@mnjenga I'm having the same error. Did you find the solution to this issue?

**Comment by mnjenga** [comment]
@frostshoxx I followed the steps as highlightd in #50 and was able to install, In a nutshell (at the moment all the samples dont seem to install via composer)

1) Clone this repository anywhere on the same server as Magento.
2) Under <magento root>/app/code, create a directory for the module you want. The name of the directory must match the value of the module's <sample module root dir>/etc/module.xml for the value of module name=
3) Copy the contents of the module to that directory.
4) Run php <magento root>/bin/magento setup:upgrade

Will be glad to assist if you require any further assistance

**Comment by frostshoxx** [comment]
Dear @mnjenga Thank you for the reply.

I have been able to install the modules sample minimal and sample shipping provider. However, when I tried to install the module for payment gateway. Without changing anything. I put the code on ../app/code/magento/samplepaymentgateway (since the module =Magento_SamplePaymentGateway)

After I run Magento setup:upgrade, I receive the following error:

```

[magento_user@mymachine public_html]$ bin/magento setup:upgrade
Cache cleared successfully
File system cleanup:
/home/magento_user/public_html/var/generation/Composer
/home/magento_user/public_html/var/generation/Magento
/home/magento_user/public_html/var/generation/Symfony
The directory '/home/magento_user/public_html/var/di/' doesn't exist - skipping cleanup
Updating modules:



  [InvalidArgumentException]
  Constant name is expected.



setup:upgrade [--keep-generated] [--magento-init-params="..."]

```

That end up hosed my Magento as well.. I need to delete the folder for the payment gateway and rerun setup:upgrade in order for the site to operate again. 

Any advice on this would be appreciate.

Thank you very much.

**Comment by sunilkumar707** [comment]
I also had same issue, because of old database tables imported from localhost.  I was trying to setup:upgrade on remote server in already installed magento database imported from localhost. I am sure this issue has something to do with database, check once.
