### ISSUE TITLE
Unable to run bin/magento setup:upgrade successfully after putting sample payment gateway on the app/code

### ISSUE THREAD

**Issue by frostshoxx** [magento/magento2-samples#70]
Dear @xcomSteveJohnson,

I have attempted to install the sample payment module per your instruction on 

https://github.com/magento/magento2-samples/issues/53#issuecomment-195049969

I put the code on /app/code/magento/samplepaymentgateway and then run setup:upgrade, but I ended getting an error:  **"Constant name is expected."**, which hosed my Magento 2.1 site.

I restored the backup, removed the module and try to run setup:upgrade again, the issue no longer occur (it came back if I brought the sample code back).

Am I missing any other steps? Please advise.

Thank you,

**Comment by frostshoxx** [comment]
Ok I figured out.. the issue has to do with \etc\di.xml

```
 <virtualType name="SamplePaymentGatewayFacade" type="Magento\Payment\Model\Method\Adapter">
        <arguments>
            **<argument name="code" xsi:type="const">\Magento\SamplePaymentGateway\Model\Ui\ConfigProvider::CODE</argument>**
            <argument name="formBlockType" xsi:type="string">Magento\Payment\Block\Form</argument>
            <argument name="infoBlockType" xsi:type="string">Magento\SamplePaymentGateway\Block\Info</argument>
            <argument name="valueHandlerPool" xsi:type="object">SamplePaymentGatewayValueHandlerPool</argument>
            <argument name="commandPool" xsi:type="object">SamplePaymentGatewayCommandPool</argument>
        </arguments>
    </virtualType>

    <!-- Configuration reader -->
    <virtualType name="SamplePaymentGatewayConfig" type="Magento\Payment\Gateway\Config\Config">
        <arguments>
            **<argument name="methodCode" xsi:type="const">\Magento\SamplePaymentGateway\Model\Ui\ConfigProvider::CODE</argument>**
        </arguments>
    </virtualType>
```

In both constant methodCode and code attribute has a leading backslash "\Magento\Sample..." The code works after remove that the leading backslash, so it becomes "Magento\Sample..."

**Comment by mgomma** [comment]
I did not work with me

**Comment by markronquillo** [comment]
Same here

**Comment by JoxieMedina** [comment]
I could make it work, just check my answer here :
 [https://magento.stackexchange.com/questions/174739/install-sample-module-payment-gateway/](https://magento.stackexchange.com/questions/174739/install-sample-module-payment-gateway/)

**Comment by ifeLight** [comment]
I made sure the module name in module.xml matched with the plugin directory name, and it worked for  me.
